evelopment: &dev
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: tcc_oficial_dev
  pool: 5
  username: postgres
  password: postgres

test: &test
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: tcc_oficial_test
  pool: 5
  username: postgres
  password: postgres

staging:
  <<: *dev

production:
  <<: *dev
